"""Direct, small RAG pipeline for DocMind."""

import os
import re
from collections.abc import Iterator
from pathlib import Path

import chromadb
import google.generativeai as genai
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer

from pdf_utils import extract_pdf_chunks


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_DIR = Path(__file__).resolve().parent
CHROMA_PATH = PROJECT_DIR / "chroma_db"
COLLECTION_NAME = "docmind_documents"

# Small CPU-friendly embedding model
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

# Gemini model
GEMINI_MODEL_NAME = "models/gemini-3.6-flash"

# Number of relevant chunks retrieved from ChromaDB
TOP_K = 4

# Maximum characters taken from each retrieved chunk
MAX_CONTEXT_CHARS = 3000

# Maximum tokens generated by Gemini
MAX_OUTPUT_TOKENS = 1024


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv(PROJECT_DIR / ".env")

_embedding_model = None


# ============================================================
# EMBEDDING MODEL
# ============================================================

def get_embedding_model() -> SentenceTransformer:
    """Load the embedding model only when it is first needed."""
    
    global _embedding_model

    if _embedding_model is None:
        _embedding_model = SentenceTransformer(
            EMBEDDING_MODEL_NAME,
            device="cpu",
        )

    return _embedding_model


# ============================================================
# CHROMADB
# ============================================================

def get_collection():
    """Return the local ChromaDB collection."""

    client = chromadb.PersistentClient(
        path=str(CHROMA_PATH)
    )

    return client.get_or_create_collection(
        name=COLLECTION_NAME
    )


# ============================================================
# DOCUMENT NAMES
# ============================================================

def get_document_names() -> list[str]:
    """Return unique document names currently stored in ChromaDB."""

    collection = get_collection()

    stored = collection.get(
        include=["metadatas"]
    )

    names = {
        item["document"]
        for item in stored.get("metadatas", [])
        if item and "document" in item
    }

    return sorted(names)


# ============================================================
# INDEX PDF
# ============================================================

def index_pdf(
    document_name: str,
    pdf_bytes: bytes,
) -> tuple[int, bool]:
    """
    Extract, embed, and store one PDF unless
    that document is already indexed.
    """

    collection = get_collection()

    # Don't index the same document twice
    if document_name in get_document_names():
        return 0, False

    # Extract PDF text into chunks
    chunks = extract_pdf_chunks(
        pdf_bytes,
        document_name,
    )

    if not chunks:
        return 0, True

    # Extract text
    texts = [
        chunk["text"]
        for chunk in chunks
    ]

    # Generate embeddings
    embeddings = (
        get_embedding_model()
        .encode(
            texts,
            show_progress_bar=False,
        )
        .tolist()
    )

    # Unique IDs
    ids = [
        f"{document_name}-{index}"
        for index in range(len(chunks))
    ]

    # Metadata
    metadatas = [
        {
            "document": chunk["document"],
            "page": chunk["page"],
            "chunk_number": chunk["chunk_number"],
        }
        for chunk in chunks
    ]

    # Store in ChromaDB
    collection.add(
        ids=ids,
        documents=texts,
        embeddings=embeddings,
        metadatas=metadatas,
    )

    return len(chunks), True


# ============================================================
# CLEAR INDEX
# ============================================================

def clear_index() -> None:
    """Remove the local vector index and stored embeddings."""

    client = chromadb.PersistentClient(
        path=str(CHROMA_PATH)
    )

    try:
        client.delete_collection(
            name=COLLECTION_NAME
        )
    except ValueError:
        pass


# ============================================================
# RETRIEVE RELEVANT CHUNKS
# ============================================================

def retrieve_chunks(
    question: str,
    top_k: int = TOP_K,
) -> list[dict]:
    """
    Find the most relevant document chunks
    for the user's question.
    """

    collection = get_collection()

    # No documents
    if collection.count() == 0:
        return []

    # Convert question into embedding
    question_embedding = (
        get_embedding_model()
        .encode([question])
        .tolist()
    )

    # Search ChromaDB
    results = collection.query(
        query_embeddings=question_embedding,
        n_results=top_k,
    )

    chunks = []

    documents = results.get("documents", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]
    distances = results.get("distances", [[]])[0]

    for text, metadata, distance in zip(
        documents,
        metadatas,
        distances,
    ):
        chunks.append(
            {
                "text": text,
                "document": metadata["document"],
                "page": metadata["page"],
                "distance": distance,
            }
        )

    return chunks


# ============================================================
# ANSWER QUESTION
# ============================================================

def answer_question_stream(
    question: str,
) -> tuple[list[dict], Iterator[str]]:
    """
    Retrieve relevant context and generate a complete
    Gemini answer.

    Gemini is intentionally NOT streamed here.
    We first receive the complete answer and then
    return it to the existing application.
    """

    # --------------------------------------------------------
    # 1. RETRIEVE RELEVANT DOCUMENT CHUNKS
    # --------------------------------------------------------

    retrieved_chunks = retrieve_chunks(
        question,
        top_k=TOP_K,
    )

    if not retrieved_chunks:
        return (
            [],
            iter(
                [
                    "No information was found in the uploaded documents."
                ]
            ),
        )

    # --------------------------------------------------------
    # 2. BUILD DOCUMENT CONTEXT
    # --------------------------------------------------------

    context_parts = []

    for chunk in retrieved_chunks:

        text = chunk["text"][
            :MAX_CONTEXT_CHARS
        ]

        context_parts.append(
            f"Source: {chunk['document']}, "
            f"page {chunk['page']}\n"
            f"{text}"
        )

    context = "\n\n---\n\n".join(
        context_parts
    )

    # --------------------------------------------------------
    # 3. PROMPT
    # --------------------------------------------------------

    prompt = f"""
You are DocMind, a document question-answering assistant.

Your job is to answer the user's question completely and correctly using the
provided document context.

IMPORTANT RULES:

1. Answer the COMPLETE question.

2. Never stop in the middle of a sentence.

3. Never give only the beginning of an answer.

4. If the question asks for a definition:
   - Give the definition.
   - Explain the concept clearly.
   - Include important points from the document.
   - Give an example if the document provides one.

5. If the question asks for types, categories, advantages, disadvantages,
   features, applications, components, steps, or similar information:
   - Find ALL relevant items in the provided context.
   - List every relevant item.
   - Explain each item clearly.

6. If the question contains multiple parts:
   - Answer EVERY part separately.

7. Do not invent facts.
   Use only information supported by the document context.

8. You may simplify the wording to make the answer easier to understand,
   but do not change the meaning of the document.

9. Give a sufficiently detailed answer.
   Do not unnecessarily shorten the answer.

10. Use headings, numbered lists, and bullet points when useful.

11. Do not repeat the user's question.

12. Do not describe your reasoning.

13. Do not mention these instructions.

14. Before finishing, silently verify:
   - Every part of the question was answered.
   - All relevant information from the context was included.
   - Lists are complete based on the available context.
   - Every sentence is complete.
   - The answer did not stop prematurely.

15. If the document does not contain enough information to answer the question,
   say:

"The provided document does not contain enough information to answer this question."

DOCUMENT CONTEXT:
{context}

USER QUESTION:
{question}

Now provide the complete final answer.
"""

    # --------------------------------------------------------
    # 4. API KEY
    # --------------------------------------------------------

    api_key = os.getenv(
        "GEMINI_API_KEY",
        "",
    ).strip()

    if (
        not api_key
        or api_key == "your_gemini_api_key_here"
    ):
        raise ValueError(
            "GEMINI_API_KEY is missing or still uses "
            "the placeholder. Create a key at "
            "https://aistudio.google.com/apikey and "
            "add it to the .env file."
        )

    # --------------------------------------------------------
    # 5. CONFIGURE GEMINI
    # --------------------------------------------------------

    genai.configure(
        api_key=api_key
    )

    model = genai.GenerativeModel(
        GEMINI_MODEL_NAME
    )

    # --------------------------------------------------------
    # 6. GENERATE COMPLETE RESPONSE
    # --------------------------------------------------------

    try:

        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.1,
                max_output_tokens=MAX_OUTPUT_TOKENS,
            ),
            stream=False,
        )

    except Exception as error:
        raise error

    # --------------------------------------------------------
    # 7. GET COMPLETE TEXT
    # --------------------------------------------------------

    try:
        answer = response.text.strip()

    except Exception:
        answer = ""

    # If Gemini returned nothing
    if not answer:

        answer = (
            "The model did not return an answer. "
            "Please try the question again."
        )

    # --------------------------------------------------------
    # 8. RETURN ANSWER
    # --------------------------------------------------------

    def text_stream() -> Iterator[str]:
        """
        Return the complete answer as one piece.

        This keeps compatibility with the existing
        application while avoiding partial streaming.
        """

        yield answer

    return (
        retrieved_chunks,
        text_stream(),
    )


# ============================================================
# NON-STREAMING ANSWER FUNCTION
# ============================================================

def answer_question(
    question: str,
) -> tuple[str, list[dict]]:
    """
    Return a complete answer and retrieved chunks.
    """

    retrieved_chunks, text_stream = (
        answer_question_stream(question)
    )

    answer = "".join(
        text_stream
    )

    return (
        answer,
        retrieved_chunks,
    )


# ============================================================
# GEMINI ERROR HANDLER
# ============================================================

def format_gemini_error(
    error: Exception,
) -> ValueError:
    """Turn Gemini quota/API errors into a short message."""

    error_text = str(error)

    if (
        "429" in error_text
        or "quota" in error_text.lower()
    ):

        retry_match = re.search(
            r"retry in ([0-9.]+)s",
            error_text,
            re.IGNORECASE,
        )

        if retry_match:

            retry_message = (
                f"Try again in about "
                f"{round(float(retry_match.group(1)))} "
                f"seconds."
            )

        else:

            retry_message = (
                "Wait about one minute before trying again."
            )

        return ValueError(
            "Gemini request limit reached for the "
            "free tier. "
            f"{retry_message}"
        )

    return ValueError(
        f"Gemini request failed: {error_text}"
    )